"""Replay every weighted head with class-wise sums, without refitting or query data."""
from pathlib import Path
import json,joblib,numpy as np
from scipy.special import expit
from sklearn.metrics import roc_auc_score,average_precision_score,brier_score_loss,balanced_accuracy_score
O=Path(__file__).resolve().parent;r=json.loads((O/'training_launch_private.json').read_text());out=Path(r['run']);source=Path(r['source_run']);designs=Path(r['design_run']);receipt=out/'independent_replay_private.json';assert not receipt.exists(),'Reuse the completed weighted-head replay.'
assert json.loads((out/'status_private.json').read_text())['state']=='PREDECLARED_CLASS_BALANCE_COMPLETE_REPLAY_PENDING';groups=json.loads((source/'groups_private.json').read_text());rows=[];pmax=lmax=smax=0.;count=0
for path in sorted((out/'models').glob('*/*.joblib')):
 h=joblib.load(path);old=joblib.load(source/'models'/path.parent.name/path.name);d=joblib.load(designs/'designs'/h['design']);g=next(g for g in groups if g['task']==path.parent.name);assert d['train_indices']==h['train_indices']==old['train_indices'] and d['validation_indices']==h['validation_indices']==old['validation_indices'] and not (set(d['train_indices'])|set(d['validation_indices']))&set(g['query'])
 x=np.asarray(d['x'],float);xv=np.asarray(d['xv'],float);y=np.asarray(d['y']);yv=np.asarray(d['yv']);assert x.shape==xv.shape==(44,288) and np.count_nonzero(y==0)==7 and np.count_nonzero(y==1)==37;assert np.allclose(h['training_class_weights'],[22/7,22/37]);scaler=h['scaler']
 if scaler is None:assert h['scale']=='raw';z=x;zv=xv
 else:
  mean=x.sum(0)/len(x);var=((x-mean)**2).sum(0)/len(x);eps=np.finfo(float).eps;constant=var<=len(x)*eps*var+(len(x)*mean*eps)**2;scale=np.sqrt(var);scale[constant]=1.;smax=max(smax,float(abs(mean-scaler.mean_).max()),float(abs(scale-scaler.scale_).max()));z=(x-mean)/scale;zv=(xv-mean)/scale
 params=h['model'].get_params();original=old['model'].get_params();assert {k:v for k,v in params.items() if k!='class_weight'}=={k:v for k,v in original.items() if k!='class_weight'} and params['class_weight']=='balanced' and original['class_weight'] is None and params['C']==1 and params['tol']==1e-10
 a=np.c_[z,np.ones(len(z))];av=np.c_[zv,np.ones(len(zv))]
 def weighted_objective(model):
  theta=np.r_[model.coef_[0],model.intercept_[0]];scores=a@theta;loss=np.logaddexp(0,scores)-y*scores;error=expit(scores)-y;gradient=sum((22/np.count_nonzero(y==v))*(a[y==v].T@error[y==v]) for v in [0,1]);weighted_loss=sum(22*loss[y==v].mean() for v in [0,1])
  if h['penalty']=='l1':penalty=abs(theta).sum();res=np.where(theta!=0,abs(gradient+np.sign(theta)),np.maximum(abs(gradient)-1,0))
  else:penalty=theta@theta/2;res=abs(gradient+theta)
  return float(weighted_loss+penalty),float(res.max()),expit(av@theta)
 new_obj,kkt,p=weighted_objective(h['model']);old_obj,old_kkt,oldp=weighted_objective(old['model']);pmax=max(pmax,float(abs(p-h['probability']).max()),float(abs(oldp-old['probability']).max()));count+=len(p);assert abs(new_obj-h['diagnostic']['weighted_summed_objective'])<1e-10 and abs(kkt-h['diagnostic']['maximum_weighted_kkt_residual'])<1e-9 and abs(old_obj-h['original_weighted_diagnostic']['weighted_summed_objective'])<1e-10
 clipped=np.clip(p,np.finfo(float).eps,1-np.finfo(float).eps);terms=-(yv*np.log(clipped)+(1-yv)*np.log1p(-clipped));ll=float(terms.mean());bll=float(sum(.5*terms[yv==v].mean() for v in [0,1]));lmax=max(lmax,abs(ll-h['metrics']['log_loss']),abs(bll-h['metrics']['balanced_log_loss']));metrics=dict(auc=float(roc_auc_score(yv,p)),average_precision=float(average_precision_score(yv,p)),log_loss=ll,balanced_log_loss=bll,brier=float(brier_score_loss(yv,p)),balanced_accuracy=float(balanced_accuracy_score(yv,p>=.5)));assert max(abs(metrics[k]-h['metrics'][k]) for k in metrics)<1e-12 and h['original_metrics']==old['metrics']
 rows.append(dict(method=h['method'],scale=h['scale'],penalty=h['penalty'],metrics=metrics,original_metrics=old['metrics'],auc_difference=metrics['auc']-old['metrics']['auc'],brier_difference=metrics['brier']-old['metrics']['brier'],weighted_objective_difference=new_obj-old_obj,new_weighted_kkt=kkt,constant_head=bool(np.count_nonzero(h['model'].coef_)==0),nonzero_coefficients=int(np.count_nonzero(h['model'].coef_)),iterations=int(h['model'].n_iter_.max()),warnings=h['warnings']))
assert len(rows)==48 and count==2112 and pmax<1e-12 and lmax<1e-12 and smax<1e-10
summary=[]
for method in ['pretrained','random']:
 for scale in ['raw','standardized']:
  for penalty in ['l1','l2']:
   items=[x for x in rows if (x['method'],x['scale'],x['penalty'])==(method,scale,penalty)];assert len(items)==6
   summary.append(dict(method=method,scale=scale,penalty=penalty,groups=6,mean_unweighted_metrics={k:float(np.mean([x['original_metrics'][k] for x in items])) for k in items[0]['metrics']},mean_balanced_metrics={k:float(np.mean([x['metrics'][k] for x in items])) for k in items[0]['metrics']},paired_auc_difference_mean=float(np.mean([x['auc_difference'] for x in items])),paired_auc_difference_range=[min(x['auc_difference'] for x in items),max(x['auc_difference'] for x in items)],paired_brier_difference_mean=float(np.mean([x['brier_difference'] for x in items])),maximum_weighted_kkt=max(x['new_weighted_kkt'] for x in items),weighted_objective_difference_range=[min(x['weighted_objective_difference'] for x in items),max(x['weighted_objective_difference'] for x in items)],constant_heads=sum(x['constant_head'] for x in items),mean_nonzero_coefficients=float(np.mean([x['nonzero_coefficients'] for x in items])),maximum_iterations=max(x['iterations'] for x in items),warnings=sum(bool(x['warnings']) for x in items)))
v=dict(state='ACTUAL_PREDECLARED_CLASS_BALANCE_INDEPENDENTLY_REPLAYED',models=48,inner_probabilities=count,maximum_probability_difference=pmax,maximum_loss_difference=lmax,maximum_scaler_difference=smax,maximum_weighted_kkt=max(x['new_weighted_kkt'] for x in rows),weighted_objective_difference_range=[min(x['weighted_objective_difference'] for x in rows),max(x['weighted_objective_difference'] for x in rows)],training_control_weight=22/7,training_case_weight=22/37,total_training_weight=44,class_totals=[22,22],class_weights_estimated_from_training_only=True,only_class_weight_changed=True,new_refits_during_replay=0,new_encoder_forwards=0,new_query_scores=0,parameter_selection=0,threshold=.5,baseline_prior=37/44,conditional_development_diagnostic=True,balanced_probabilities_not_population_risk=True,methods=summary);receipt.write_text(json.dumps(v,indent=2));print(json.dumps(v))
