"""Independent class-wise replay of all relative-L1 saved models and training thresholds."""
from pathlib import Path
import json,joblib,numpy as np
from scipy.special import expit
from sklearn.metrics import roc_auc_score,average_precision_score,brier_score_loss,balanced_accuracy_score
O=Path(__file__).resolve().parent;r=json.loads((O/'training_launch_private.json').read_text());out=Path(r['run']);source=Path(r['source_run']);designs=Path(r['design_run']);receipt=out/'independent_replay_private.json';assert not receipt.exists(),'Reuse the completed relative-L1 replay.'
assert json.loads((out/'status_private.json').read_text())['state']=='PREDECLARED_RELATIVE_L1_COMPLETE_REPLAY_PENDING';groups=json.loads((source/'groups_private.json').read_text());rows=[];pmax=lmax=smax=tmax=0.;count=0
for path in sorted((out/'models').glob('*/*.joblib')):
 h=joblib.load(path);old=joblib.load(source/'models'/path.parent.name/h['original_model_file']);d=joblib.load(designs/'designs'/h['design']);g=next(g for g in groups if g['task']==path.parent.name);assert d['train_indices']==h['train_indices']==old['train_indices'] and d['validation_indices']==h['validation_indices']==old['validation_indices'] and not (set(d['train_indices'])|set(d['validation_indices']))&set(g['query'])
 x=np.asarray(d['x'],float);xv=np.asarray(d['xv'],float);y=np.asarray(d['y']);yv=np.asarray(d['yv']);assert x.shape==xv.shape==(44,288) and np.count_nonzero(y==0)==7 and np.count_nonzero(y==1)==37;scaler=h['scaler']
 if scaler is None:assert h['scale']=='raw';z=x;zv=xv
 else:
  mean=x.sum(0)/len(x);var=((x-mean)**2).sum(0)/len(x);eps=np.finfo(float).eps;constant=var<=len(x)*eps*var+(len(x)*mean*eps)**2;scale=np.sqrt(var);scale[constant]=1.;smax=max(smax,float(abs(mean-scaler.mean_).max()),float(abs(scale-scaler.scale_).max()));z=(x-mean)/scale;zv=(xv-mean)/scale
 a=np.c_[z,np.ones(len(z))];av=np.c_[zv,np.ones(len(zv))];threshold=float(abs(11*(a[y==0].mean(0)-a[y==1].mean(0))).max());fraction=h['fraction'];assert fraction in [1.,.3,.1,.03];lam=fraction*threshold;tmax=max(tmax,abs(threshold-h['lambda_max']));assert abs(threshold-h['lambda_max'])<1e-10 and abs(lam-h['lambda_'])<1e-10 and threshold>0
 params=h['model'].get_params();original=old['model'].get_params();assert {k:v for k,v in params.items() if k!='C'}=={k:v for k,v in original.items() if k!='C'} and np.isclose(params['C'],1/lam,rtol=1e-9,atol=1e-12) and params['class_weight']=='balanced' and params['l1_ratio']==1
 def objective(model):
  theta=np.r_[model.coef_[0],model.intercept_[0]];scores=a@theta;loss=np.logaddexp(0,scores)-y*scores;error=expit(scores)-y;gradient=sum((22/np.count_nonzero(y==v))*(a[y==v].T@error[y==v]) for v in [0,1]);res=np.where(theta!=0,abs(gradient+lam*np.sign(theta)),np.maximum(abs(gradient)-lam,0));value=sum(22*loss[y==v].mean() for v in [0,1])+lam*abs(theta).sum();return float(value),float(res.max()),expit(av@theta)
 value,kkt,p=objective(h['model']);reference,reference_kkt,oldp=objective(old['model']);pmax=max(pmax,float(abs(p-h['probability']).max()),float(abs(oldp-old['probability']).max()));count+=len(p);assert abs(value-h['diagnostic']['weighted_objective'])<1e-9 and abs(kkt-h['diagnostic']['maximum_weighted_kkt'])<1e-9 and abs(reference-h['same_lambda_original_diagnostic']['weighted_objective'])<1e-9
 terms=-(yv*np.log(np.clip(p,np.finfo(float).eps,1-np.finfo(float).eps))+(1-yv)*np.log1p(-np.clip(p,np.finfo(float).eps,1-np.finfo(float).eps)));ll=float(terms.mean());bll=float(sum(.5*terms[yv==v].mean() for v in [0,1]));lmax=max(lmax,abs(ll-h['metrics']['log_loss']),abs(bll-h['metrics']['balanced_log_loss']));metrics=dict(auc=float(roc_auc_score(yv,p)),average_precision=float(average_precision_score(yv,p)),log_loss=ll,balanced_log_loss=bll,brier=float(brier_score_loss(yv,p)),balanced_accuracy=float(balanced_accuracy_score(yv,p>=.5)));assert max(abs(metrics[k]-h['metrics'][k]) for k in metrics)<1e-12 and h['original_metrics']==old['metrics']
 zero_gap=value-44*np.log(2) if fraction==1 else None
 if fraction==1:assert abs(zero_gap)<1e-9
 rows.append(dict(method=h['method'],scale=h['scale'],fraction=fraction,lambda_max=threshold,lambda_=lam,metrics=metrics,original_metrics=old['metrics'],auc_difference=metrics['auc']-old['metrics']['auc'],brier_difference=metrics['brier']-old['metrics']['brier'],same_lambda_objective_difference=value-reference,weighted_kkt=kkt,constant_head=bool(np.count_nonzero(h['model'].coef_)==0),nonzero_coefficients=int(np.count_nonzero(h['model'].coef_)),probability_span=float(np.ptp(p)),fraction1_zero_objective_gap=zero_gap,iterations=int(h['model'].n_iter_.max()),warnings=h['warnings']))
assert len(rows)==96 and count==4224 and pmax<1e-12 and lmax<1e-12 and smax<1e-10
summary=[]
for method in ['pretrained','random']:
 for scale in ['raw','standardized']:
  for fraction in [1.,.3,.1,.03]:
   items=[x for x in rows if (x['method'],x['scale'],x['fraction'])==(method,scale,fraction)];assert len(items)==6
   summary.append(dict(method=method,scale=scale,fraction=fraction,groups=6,mean_fixed_C1_metrics={k:float(np.mean([x['original_metrics'][k] for x in items])) for k in items[0]['metrics']},mean_relative_metrics={k:float(np.mean([x['metrics'][k] for x in items])) for k in items[0]['metrics']},paired_auc_difference_mean=float(np.mean([x['auc_difference'] for x in items])),paired_auc_difference_range=[min(x['auc_difference'] for x in items),max(x['auc_difference'] for x in items)],paired_brier_difference_mean=float(np.mean([x['brier_difference'] for x in items])),lambda_max_range=[min(x['lambda_max'] for x in items),max(x['lambda_max'] for x in items)],lambda_range=[min(x['lambda_'] for x in items),max(x['lambda_'] for x in items)],maximum_weighted_kkt=max(x['weighted_kkt'] for x in items),same_lambda_objective_difference_range=[min(x['same_lambda_objective_difference'] for x in items),max(x['same_lambda_objective_difference'] for x in items)],constant_heads=sum(x['constant_head'] for x in items),mean_nonzero_coefficients=float(np.mean([x['nonzero_coefficients'] for x in items])),maximum_probability_span=max(x['probability_span'] for x in items),maximum_iterations=max(x['iterations'] for x in items),warnings=sum(bool(x['warnings']) for x in items)))
zero=[x for x in rows if x['fraction']==1];v=dict(state='ACTUAL_PREDECLARED_RELATIVE_L1_INDEPENDENTLY_REPLAYED',models=96,inner_probabilities=count,maximum_probability_difference=pmax,maximum_loss_difference=lmax,maximum_scaler_difference=smax,maximum_independent_lambda_max_difference=tmax,maximum_weighted_kkt=max(x['weighted_kkt'] for x in rows),same_lambda_objective_difference_range=[min(x['same_lambda_objective_difference'] for x in rows),max(x['same_lambda_objective_difference'] for x in rows)],fraction1_zero_reference_heads=len(zero),fraction1_maximum_zero_objective_gap=max(abs(x['fraction1_zero_objective_gap']) for x in zero),fraction1_maximum_probability_span=max(x['probability_span'] for x in zero),lambda_max_estimated_from_training_only=True,fractions=[1.,.3,.1,.03],new_refits_during_replay=0,new_encoder_forwards=0,new_query_scores=0,parameter_selection=0,threshold=.5,baseline_prior=37/44,conditional_development_diagnostic=True,balanced_probabilities_not_population_risk=True,methods=summary);receipt.write_text(json.dumps(v,indent=2));print(json.dumps(v))
